parameters:

services:
  product_manager:
    class: AppBundle\Manager\ProductManager
    arguments:
      - '@doctrine.orm.entity_manager'
  comment_manager:
    class: AppBundle\Manager\CommentManager
    arguments:
      - '@doctrine.orm.entity_manager'

  twig_extension:
    class: AppBundle\Twig\AppExtension
    tags:
      - {name: twig.extension}